### ISSUE TITLE
demo: improve endpoint configuration

### ISSUE THREAD

**Issue by felixge** [tus/tus.io#1]
Right now you have to edit the `js/main.js` file to change the url endpoint used for the demo. This config should be moved to _site.yml and be easy to overwrite for local development.

Problems:
* Seems like `.js` files are not interpreted as templates by jekyll, so `{{ site.demo.url }}` isn't accessible
* Jekyll seems to have no concept of environment configs, so we'll have to come up with something for that ourselves.

This is not urgent, but a nice to have.

**Comment by kvz** [comment]
If you want to target local (or any other) tus servers, you can change Jekyll's `tusd_endpoint` varialble. You can also pass this in at runtime as you can overlay configuration. 

This is good enough for our purposes, so I'm resolving this one now
