### ISSUE TITLE
unable to install npm dependencies 

### ISSUE THREAD

**Issue by sarvaratchagan** [tus/tus.io#105]
I cloned this repository in my local machine & when I try to install npm dependencies I'm getting some issues. Could you please help me ? Herewith I attached screen shot for your reference.

![screenshot_1](https://cloud.githubusercontent.com/assets/7565739/20987513/fadb1f72-bcf2-11e6-9678-31baebc0bd81.jpg)

**Comment by Acconut** [comment]
@kvz, could you help us with this issue?

**Comment by kvz** [comment]
Hi,

tus.io is only the website. Did you clone it because you wanted to propose a change to our website? We use https://github.com/kvz/lanyon for web development which does not support Windows, which is likely the cause of your trouble :/

**Comment by kvz** [comment]
If you just want to use tus  though, the good news is that you don't need the tus.io repository

**Comment by sarvaratchagan** [comment]
Not for change. I understood the thing after long R&D. because there is no windows support in "lanyon". Recently we have a requirement to implement resumable upload functionality. I need some help on that 

1) is there any existing angular js version available for "tus-js-client"
2) how can we implement encryption & decryption

Thanks !

**Comment by Acconut** [comment]
> because there is no windows support in "lanyon". 

We are going to look into how we can add support for Windows in Lanyon. If you are interested in this topic, you may subscribe to https://github.com/kvz/lanyon/issues/2.

> is there any existing angular js version available for "tus-js-client". If not I can contribute on that.

There is no Angular-specific project but tus-js-client will run in all modern browsers. Are there any specific requirements for Angular to use third-party libraries?

> how can we implement encryption & decryption

Which kind of encryption do you think of? Server- or client-side? Please describe this question in more detail.

> will it support upload multiple files simultaneously

Yes, it already does.

**Comment by sarvaratchagan** [comment]
Hello @Acconut , We have a requirement to develop a product like dropbox. Here end user can upload very large files and store their information in cloud storage. 

Q2 : I tried samples it's showing only one progress indicator. I need to show progress indicator separately each uploading files. If there is any existing components available we can use it without much effort. Herewith I have attached a screenshot for your reference.

Q3 : Yes Like MD5, SparkMD5 or else if you have any suggestion, please share with me. Encryption should be done in client side & we have to decrypt back and store it in cloud storage secure data.

Thanks-
Sarva

**Comment by kvz** [comment]
Hi there. It seems like you're interest in UI, tus-js-client is just the core of resumable file uploading and offers no progress-bar by default, only progress events. If you're interested in a ready-to-rock UI, http://uppy.io is the first file uploader with support for tus (but it's a work in progress).

As for encryption, MD5 only offers (weak) hashing, so it cannot be used for anything else than e.g. error checking. If you want encryption you could look into e.g. AES, but it is a hard problem to solve in a good way, considering you want to have a secret used for decryption, both on the server and client.

**Comment by sarvaratchagan** [comment]
Hello @kvz , Thanks for your suggestion. I want discuss with you bit more. Is there any channel available to talk for our team ?

**Comment by Acconut** [comment]
@sarvaratchagan We have a tus-related channel on Slack. If you are keen on joining, you can send me a mail at marius@transloadit.com and I will get you invited.

**Comment by Acconut** [comment]
> Yes Like MD5, SparkMD5 or else if you have any suggestion, please share with me.

As @kvz said, MD5 is no encryption algorithm, it's used for checksums.

> Encryption should be done in client side & we have to decrypt back

That pretty much sounds as plain old HTTPS to me. It allows you to securely communicate between the client and server.

**Comment by sarvaratchagan** [comment]
@Acconut Thank you & I have sent you mail. Please invite me.
