### ISSUE TITLE
Demo doesn't seem to be working

### ISSUE THREAD

**Issue by acrispino** [tus/tus.io#106]
I've been looking into tus lately. The demo page was working a few days ago, but isn't at the moment. I get this error:

![https://i.imgur.com/74bpqT0.png](https://i.imgur.com/74bpqT0.png)

Relevant lines from the chrome dev console:
```
XMLHttpRequest cannot load http://master.tus.io/files/. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://tus.io' is therefore not allowed access.
XHR failed loading: POST "http://master.tus.io/files/".
```

chrome network log shows an OPTIONS request, but it seems to be missing the CORS + tus headers.

As an aside: does tus-js-client provide a way to know in which 'phase' an error has occurred? I might like to tell a user one thing if an error has happened while uploading, and a different thing if the upload could not be started at all.

**Comment by Acconut** [comment]
Thank you for reporting. We changed the configuration of our proxy which caused this problem when uploading. However, this has been addressed by now and should work as expected.

>  does tus-js-client provide a way to know in which 'phase' an error has occurred? I might like to tell a user one thing if an error has happened while uploading, and a different thing if the upload could not be started at all.

Not directly. You may want to listen to the progress event and if an error occurs after the corresponding listener has been invoked, you can assume that the error appeared during the upload.
