### ISSUE TITLE
tus.py: A new Python client

### ISSUE THREAD

**Issue by cenkalti** [tus/tus.io#107]
Hello,

I have written a new Python client for Tus protocol.

https://github.com/cenkalti/tus.py

Not every extension is supported but it is working okay for months so it is mature enough. We are using it at https://put.io internally. Also it is a dependency for our client library [putio.py](https://github.com/cenkalti/putio.py/blob/86c0bede1fbe3003e948eb905d16674a235557fa/setup.py#L19). A review from you guys would be good though.

Would you like to list it on https://tus.io/implementations.html page?

I can send a PR if you want.

**Comment by kvz** [comment]
Hi,

Thanks for your interest in tus! If you can add the license and version details, we'd be happy to merge such a PR.

All the best, Kevin

**Comment by Acconut** [comment]
I am very pleased to hear this! Looking sharp :+1: I will definitely have a look at it, even if my experience in Python is far below rudimentary. In addition, @ifedapoolarewaju also recently released a Python client (https://github.com/ifedapoolarewaju/tus-py-client) so he could probably give some better feedback, if he wants to :)
