### ISSUE TITLE
Serve static file without extension?

### ISSUE THREAD

**Issue by tudeptrai102** [tus/tus.io#119]
If you save files without extension, so how web server ( ex: IIS) can serve static file (image)? (for best performance on display?)
Any config to add extension to file?

**Comment by kvz** [comment]
Hi, did you mean to post this to tusd or node-tus-server maybe? 

One idea is to use the post hook to take the extension from the metadata and then save the file on final storage along with the extension, am i right @Acconut ?

**Comment by tudeptrai102** [comment]
As tus-node-server, they have a config like this https://github.com/tus/tus-node-server#custom-file-names
It's help web server can serve file as static file (known extension), We do not need to try read metadata, then write file to client manual. Performance will be better?

**Comment by tudeptrai102** [comment]
Oh sorry, i just understand @kvz  say. Close issue, thanks...
