### ISSUE TITLE
Recommend express-tus as a node.js server implementation

### ISSUE THREAD

**Issue by gajus** [tus/tus.io#145]
https://github.com/gajus/express-tus

**Comment by Acconut** [comment]
I'm sorry to read that you are unsatisfied with tus-node-server and tusd and can very much understand your concerns. We would like to invest more resources into our implementations but our own time is also limited, so in particular tus-node-server is in a bad state.

If you want, you can open a PR to add express-tus to the list of implementations at https://github.com/tus/tus.io/blob/master/_content/implementations.md.

What's the state of express-tus? Is it production-ready yet? Do you plan on including more storage options (e.g. disk and S3) such as tus-node-server and tusd do?

**Comment by gajus** [comment]
> What's the state of express-tus? Is it production-ready yet? Do you plan on including more storage options (e.g. disk and S3) such as tus-node-server and tusd do? Do you plan on supporting it in the long term? Depending on your answers, we can talk about recommending your project to users.

As the [README.md explains](https://github.com/gajus/express-tus#motivation), `express-tus` does not (and will not) support any storage methods. Those can be built by anyone in the community. The purpose of `express-tus` to abstract the protocol requirements.

You can see all my open-source contributions https://github.com/gajus. They are all maintained.

**Comment by Acconut** [comment]
>  As the README.md explains, express-tus does not (and will not) support any storage methods.

Makes sense as a design decision but in that case it is not a drop-in replacement for tus-node-server? Or do storage backends already exist?

Feel free to open a PR to adding express-tus to the list of implementations and to tus-node-server's README :) And thank you for contributing to the tus community!

**Comment by gajus** [comment]
> Makes sense as a design decision but in that case it is not a drop-in replacement for tus-node-server? Or do storage backends already exist?

`tus-node-server` could use `express-tus` or it could provide just the storage implementations compatible with `express-tus`.

**Comment by Acconut** [comment]
tus-node-server is maintained again and in a much better shape. Thank you for working on express-tus, but I don't think we just recommend it as a replacement for tus-node-server.
