### ISSUE TITLE
Demo file upload resume or cancel is not working

### ISSUE THREAD

**Issue by Ghoughpteighbteau** [tus/tus.io#155]
https://streamable.com/u01b4u

I can't start or resume a file I am uploading. I've tested this on three machines, two linux, one windows, multiple browsers each.

**Comment by Acconut** [comment]
Thank you for reporting. I am not able to reproduce this right now. Could you try again and see if this was a temporary failure?

**Comment by Ghoughpteighbteau** [comment]
ok, tried it again: 

https://streamable.com/ciqv5k

**Comment by Ghoughpteighbteau** [comment]
any thoughts on this one? I can provide diagnostics if you need it. 

I've asked a few people to test this on their machine and it's not working for them, your environment may be letting it work on your machine somehow.

**Comment by Acconut** [comment]
Ah, ok, thank you very much for the second video. It helped me understand what problem you were talking about and how to fix it. A patch for this is currently deploying and should be live soon.

**Comment by Acconut** [comment]
This fix is live and the demo should be working now again :tada:
