### ISSUE TITLE
Can't visit the website as Bitdefender complains

### ISSUE THREAD

**Issue by Cigoler** [tus/tus.io#170]
Here's the notification:

```
Infected web resource detected
one minute ago

Feature:
Online Threat Prevention

We blocked this dangerous page for your protection:
https://tus.io/
Accessed by: brave.exe
Dangerous pages attempt to install software that can harm the device, gather personal information or operate without your consent.
```

just fyi, not sure where or why you're blacklisted?

**Comment by Acconut** [comment]
Thank you very much for letting us know! People are always uploading dubious stuff to our public demo and even virus scanners can't catch everything. I have submitted our website to https://www.bitdefender.com/submit for a review and let's hope it get unblocked soon.

**Comment by kvz** [comment]
We're in the process of moving our demo upload target to a different domain, that will also help.
