### ISSUE TITLE
Inaccesible menu

### ISSUE THREAD

**Issue by Acconut** [tus/tus.io#171]
When the browser has a width of about 946px, the menu icon is hidden behind the GitHub icon on the upper right corner and the navigation is not accessible. When the browser is wider the full navigation items get shown correctly. Also, when the browser width is smaller, the GitHub icon gets hidden correctly. So this seems like an inconsistency in the limits for media queries in CSS.

 ![image](https://user-images.githubusercontent.com/1375043/94417134-fce0d700-017f-11eb-8822-64d136dcc047.png)

**Comment by nqst** [comment]
Good point, thanks! Fixed 👌

**Comment by Acconut** [comment]
Thank yoou very much :heart:
