### ISSUE TITLE
Wrong certificate for tus.io

### ISSUE THREAD

**Issue by StefanWallin** [tus/tus.io#209]
Hi! Newcomer here! 👋 

It seems that when visiting tus.io you get a certificate for github.com instead of one meant for your domain.

<img width="319" alt="Screenshot 2021-10-13 at 20 35 10" src="https://user-images.githubusercontent.com/457653/137192920-a09203de-4059-4ebc-b9c3-cffc018d44f6.png">
<img width="684" alt="Screenshot 2021-10-13 at 20 35 17" src="https://user-images.githubusercontent.com/457653/137192925-83dc60ba-5871-4c8c-aafa-e5609b5a237d.png">

**Comment by Acconut** [comment]
Thanks for the report! It works for me on my laptop and phone, but @kvz also mentioned that he had problems. Could you look into that, Kevin?

**Comment by Acconut** [comment]
Great to hear, Kevin! @StefanWallin Let us know if you are still encountering the problem. If so, we will reopen this issue and investigate.
