### ISSUE TITLE
Demo page needs <3

### ISSUE THREAD

**Issue by kvz** [tus/tus.io#25]
Here's a screen with some suggestions:

![](https://dl.dropboxusercontent.com/s/fjrespiu08508s6/2015-08-20%20at%2022.49%202x.png?dl=0)

About the platforms... Could we use the ones mentioned here for starters? https://travis-ci.org/tus/tus-js-client/builds/68939798

**Comment by kvz** [comment]
> About the platforms... Could we use the ones mentioned here for starters? https://travis-ci.org/tus/tus-js-client/builds/68939798

Taking care of this one myself --^

**Comment by Acconut** [comment]
You can find a list of browser which this is tested against in https://github.com/tus/tus-js-client/blob/master/.zuul.yml.

**Comment by Acconut** [comment]
@kvz The best way (but not the prettiest) would be to embed Saucelabs' browser matrix: https://saucelabs.com/browser-matrix/marius_transloadit.svg

**Comment by kvz** [comment]
Not sure about that svg, it's cool, but a bit ugly indeed.

**Comment by Acconut** [comment]
The browser matrix has been addressed in bd6a453d9483a8fa0530cec4dea7921000d4f603.

**Comment by Acconut** [comment]
All your suggestions have been implemented and are live :)
