### ISSUE TITLE
Companies that (plan to) use tus

### ISSUE THREAD

**Issue by kvz** [tus/tus.io#28]
I think it would be cool to add a "Used by" section to the homepage with companies listed in this ticket. So please leave a comment here if you (plan to) use tus in production.

**Comment by kvz** [comment]
[Transloadit](https://transloadit.com)

**Comment by kvz** [comment]
This has been addressed in https://github.com/tus/tus.io/compare/658bd572ae0df0bdd3bd857dbd3860628b67b890...0472845fef4c6e4526e19d6592dd7f58968205d3, visitors can now directly submit PRs to contribute their logos.

**Comment by khangtoh** [comment]
We at @picocandy have been using @picocandy/rubytus in production since 2013

**Comment by kvz** [comment]
If you want you logo up there, please add it here https://github.com/tus/tus.io/edit/master/_data/logos.yml
