### ISSUE TITLE
Make blog posts look prettier

### ISSUE THREAD

**Issue by kvz** [tus/tus.io#29]
Not sure how yet, but I feel a page like http://127.0.0.1:4000/blog/2015/09/19/project-status/ looks a bit unbalanced and is pretty hard to digest:

![screencapture-127-0-0-1-4000-blog-2015-09-19-project-status-1442651755078](https://cloud.githubusercontent.com/assets/26752/9975364/4daca1a0-5eba-11e5-95ea-4937f3fbb984.png)

Any ideas are welcome

**Comment by Acconut** [comment]
I added some indention to the paragraphs and lists, while making the space between sentences smaller. Also, headings have a light line beneath them.

For me personal, it's better to keep sentences in a paragraph together and not start a new line after a sentence stops. This makes it easier to read and symbolises that this block of texts speaks about a specific topic. It can be hard to do that, but I think it looks more professional.

![tus-blog-improv](https://cloud.githubusercontent.com/assets/1375043/9976722/a2ed5f38-5eec-11e5-820d-5aa6917d71c7.png)

**Comment by kvz** [comment]
Much better! What about the font face itself, are we happy with that? It feels a bit dull to me, not very polished either. And maybe it too black. thoughts?

**Comment by fahad19** [comment]
Current font used is Proxima Nova. Works great on apps, but its use on blog posts can be questionable.

Other suggestions that I propose, if everyone really wishes for a change:

* Lato: https://www.google.com/fonts/specimen/Lato
* Vollkorn: https://www.google.com/fonts/specimen/Vollkorn (I really prefer serif fonts, those with curvy ends, for posts)
* Roboto Slab: https://www.google.com/fonts/specimen/Roboto+Slab

**Comment by fahad19** [comment]
For paid fonts via TypeKit, I am a fan of FF Tisa Pro: https://typekit.com/fonts/ff-tisa-web-pro/n4/wfs

**Comment by kvz** [comment]
Transloadit purchased a typekit license iirc for the shiny site - could we repurpose it for tus?

**Comment by kvz** [comment]
This was resolved in #35
