### ISSUE TITLE
Using Jekyll for assets?

### ISSUE THREAD

**Issue by kvz** [tus/tus.io#30]
I see we're using node dependencies to build less->css.

Would it make sense to use Jekyll's built in stuff for this?
I'm not sure if the `less` node module is faster or anything. But it would be nice to just do `jekyll serve --watch`, and not only have previews of html changes but also layout. 

I realize one could now run `npm scripts build:watch`, but having a unified toolchain would be nice?

**Comment by fahad19** [comment]
I would be in favour of doing it all via one command, but no clue how to do it via Jekyll.

**Comment by kvz** [comment]
Good to know you'd be on board, I'll see if there's an easy route to make it happen.

**Comment by kvz** [comment]
This has been completed in https://github.com/tus/tus.io/compare/658bd572ae0df0bdd3bd857dbd3860628b67b890...0472845fef4c6e4526e19d6592dd7f58968205d3

Please run `make preview` to see how if it works locally - and let me know how it went @Acconut @fahad19.
