### ISSUE TITLE
Changing IP adress - resume possible?

### ISSUE THREAD

**Issue by hpvd** [tus/tus.io#90]
This is really nice up-write of why and how TUS http://tus.io/blog/2015/11/16/tus.1.0/

just one question is open: could TUS also handle the change of an IP address?

e.g.
1) you start an upload at home in your own wifi and take your notebook with you to work where is another wifi => could the upload in new wifi with new IP address be resumed?

2) you start an upload with your mobile 3G connection not having noticed that you are not in wifi   when noticing it you switch to wifi

=>
if this could be handle: it would be perfect to  have this documented on website
if not - we should strongly think about it!

**Comment by Acconut** [comment]
> This is really nice up-write of why and how TUS

Thank you a lot :)

> 1) you start an upload at home in your own wifi and take your notebook with you to work where is another wifi => could the upload in new wifi with new IP address be resumed?

Yes, the tus protocol on it's own makes absolutely no assumptions about the IP address staying the same. As long as the server does not put additional constraints, which we highly recommend against, it is absolutely possible and also wanted by us.

> 2) you start an upload with your mobile 3G connection not having noticed that you are not in wifi when noticing it you switch to wifi

Same as above. Switching the network is absolutely possible by the protocol itself. The client implementations, however, need to handle these cases correctly.

> it would be perfect to have this documented on website

That's some great feedback. I will try to integrate this, thank you :)
