### ISSUE TITLE
The demo doesn't seem to work

### ISSUE THREAD

**Issue by janko-m** [tus/tus.io#93]
1. Start uploading a large file (~200MB)
1. Leave it for some time (before it gets to half)
1. Close the tab and reopen it
1. Choose the same file again
1. Upload starts from the beginning

Also, it takes really long for the upload to start (maybe 6-8 seconds), I was checking the network activity, but for some reason couldn't find what was taking so much time.

**Comment by Acconut** [comment]
Thank you for reporting this. Unfortunately, I will not be able to look into this issue for the next two weeks. Meanwhile, may you be able to check whether your browser supports localStorage? Some browsers, e.g. Chrome disallow localStorage if you are in a private browsing session.

**Comment by janko-m** [comment]
No problem, I'm using the latest Chrome (51.x) with a regular browsing session.

**Comment by Acconut** [comment]
I tried to reproduce this multiple times but were not able to achieve the same observations as you did, both the non-resuming issue and the slow start. Do these problems still occur for you?

**Comment by janko-m** [comment]
I tried again now, and was getting the same behaviour. And then I tried with a different file, and it worked perfectly. When I realized which kind of file I was using, I facepalmed.

I turns out I was using a Mac .app file which I was actually running in the background, so its contents were changing. This also explains the delayed starting time, because it's probably difficult to calculate "last modified" time of something that's actually a directory. That was the first large file that came under my fingers when I wanted to try the demo, and it turned out to be the worst possible file. Sorry for the false alarm 😄

**Comment by Acconut** [comment]
Haha, absolutely no problem. I am pleased to hear that you were able to figure it out :)
FYI, tus-js-client (the client library behind the demo) will start a new upload for the same file if its fingerprint changes. The current mechanism for calculating this value is a bit naive: https://github.com/tus/tus-js-client/blob/master/lib/fingerprint.js. Here you can also see that a changed size or modification time will trigger a new reupload.
