### ISSUE TITLE
remove Client eahydra/tusclient

### ISSUE THREAD

**Issue by eahydra** [tus/tus.io#97]
Please remove Client/eahydra/tusclient(https://github.com/eahydra/tusclient)
I don't maintain the code.

**Comment by Acconut** [comment]
We're sad to hear but obviously accept your decision. Just out of curiosity, did you delete the actual repository? If so, may I why you decided against keeping the non-maintained code public?

**Comment by eahydra** [comment]
I haven't been following TUS.  And When I review the code, the client implementation is so poor. I think need the other one re-implement the client and support new version of TUS Protocol, so I delete the repo.
